spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5434/twitter_db
    username: admin
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
logging:
  level:
    org:
      springframework:
        security: debug
