version: '3'

services:
  postgres:
    container_name: twitter_db_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=twitter_db
    ports:
      - 5434:5432